[package]
name = "search_space_visualization"
version = "0.1.0"
authors = ["Tim \"S.D.Eagle\" Zeitz <dev.tim.zeitz@gmail.com>"]

[dependencies]
bmw_routing_engine = { path = "../engine" }
svg = "0.5.6"
rand = "0.3"
getopts = "0.2"
