[package]
name = "bmw_routing_engine"
version = "0.1.0"
authors = ["Tim 'S.D.Eagle' Zeitz <dev.tim.zeitz@gmail.com>"]
edition = "2018"
build = "build.rs"

[features]
default = []
tdcch-query-detailed-timing = []
tdcch-stall-on-demand = []
tdcch-approx = []
tdcch-approx-imai-iri = ["tdcch-approx"]

[dependencies]
time = "^0.1.40"
nav-types = "^0.3.0"
csv = "^1.0.2"
glob = "^0.2.11"
rand = "^0.6.1"
serde_json = "^1.0.35"

[build-dependencies]
built = "^0.3.0"
