[package]
name = "bmw_routing_engine"
version = "0.1.0"
authors = ["Tim \"S.D.Eagle\" Zeitz <dev.tim.zeitz@gmail.com>"]
edition = "2018"

[dependencies]
time = "0.1.38"
nav-types = "0.3.0"
postgres = "0.15"
csv = "^1.0.0-beta.4"
glob = "0.2.11"
num-traits = "^0.2.5"

[dev-dependencies]
criterion = { version = "0.2", features=['real_blackbox'] }

[[bench]]
name = "mod_benchmark"
harness = false
